// Generated by tools/extract_teo_sprites.py. Do not edit by hand.
export const TEO_CELL = 128;
export const TEO_COLS = 12;
export const TEO_ROWS = 4;
export const TEO_GROUPS = {
  "idle": {
    "start": 0,
    "count": 7
  },
  "look": {
    "start": 7,
    "count": 2
  },
  "scratch": {
    "start": 9,
    "count": 2
  },
  "happy": {
    "start": 11,
    "count": 3
  },
  "lick": {
    "start": 14,
    "count": 3
  },
  "yawn": {
    "start": 17,
    "count": 3
  },
  "lie": {
    "start": 20,
    "count": 4
  },
  "sleep": {
    "start": 24,
    "count": 7
  },
  "drag": {
    "start": 31,
    "count": 4
  },
  "faces": {
    "start": 35,
    "count": 9
  }
} as const;
